### ISSUE TITLE
Regenerate raincatcher-portal repo

### ISSUE THREAD

**Issue by davidffrench** [feedhenry-raincatcher/raincatcher-portal#2]
This repo has not been regenerated since updating the dependencies with security vulnerabilities here (https://github.com/feedhenry-raincatcher/raincatcher-angularjs/tree/master/demo/portal)

**Comment by wtrocki** [comment]
@davidffrench This repository is something we provide as part of the release. It's directy what we deliver to our user base. When users start using RainCatcher they setting on some specific release. Once they do they are responsible for maintaining their package.json files to be up to date. 

TL:DR - this repo is only updated in controlled manner once per RainCatcher release that happens every sprint.

**Comment by davidffrench** [comment]
@wtrocki thanks for the explanation, that makes perfect sense.
